quarkus:
  log:
    level: INFO

  oidc:
    auth-server-url: http://localhost:7080/realms/balhom-realm
    client-id: balhom-client
    application-type: service

  mongodb:
    connection-string: mongodb://admin:password@localhost:27017
    database: balHomStatisticsDB

  smallrye-openapi:
    info-title: Statistics API
    path: /openapi
    security-scheme: jwt

  swagger-ui:
    path: /swagger

  rest-client:
    currency-profiles-api:
      url: http://localhost:8081
      scope: jakarta.inject.Singleton

kafka:
  bootstrap:
    servers: PLAINTEXT_HOST://localhost:9092
