quarkus:
  mongodb:
    database: balHomStatisticsDB

mp:
  messaging:
    incoming:
      transaction-events:
        connector: smallrye-kafka
        topic: transaction-events
        group:
          id: statistics-group
      currency-profile-events:
        connector: smallrye-kafka
        topic: currency-profile-events
        group:
          id: statistics-group
