quarkus:
  log:
    level: DEBUG
  oidc:
    auth-server-url: http://localhost:7080/realms/balhom-realm
    client-id: balhom-client
    application-type: service
  smallrye-openapi:
    info-title: Statistics API
    path: /openapi
    security-scheme: jwt
  swagger-ui:
    path: /swagger

kafka:
  bootstrap:
    servers: PLAINTEXT_HOST://localhost:29092

mp:
  messaging:
    incoming:
      transaction-events:
        connector: smallrye-kafka
        topic: transaction-events
        group:
          id: statistics-group
      currency-profile-events:
        connector: smallrye-kafka
        topic: currency-profile-events
        group:
          id: statistics-group
