quarkus:
  banner:
    path: banner.txt
  http:
    host: 0.0.0.0
    port: 8083
    cors: true
    idle-timeout: 5m
  mongodb:
    uuid-representation: STANDARD

kafka:
  consumer:
    reconnect:
      backoff:
        ms: 1000
        max:
          ms: 10000
    retry:
      backoff:
        ms: 1000
    request:
      timeout:
        ms: 30000
    session:
      timeout:
        ms: 30000

mp:
  messaging:
    incoming:
      transaction-events:
        connector: smallrye-kafka
        topic: transaction-events
        group:
          id: statistics-group
      currency-profile-events:
        connector: smallrye-kafka
        topic: currency-profile-events
        group:
          id: statistics-group
