package org.balhom.statisticsapi.modules.statistics.infrastructure.persistence.mongo

import io.quarkus.mongodb.panache.kotlin.PanacheMongoRepository
import jakarta.enterprise.context.ApplicationScoped
import org.balhom.statisticsapi.modules.statistics.infrastructure.persistence.mongo.data.YearlySavingsStatisticMongoEntity

@ApplicationScoped
class YearlySavingsStatisticMongoRepository : PanacheMongoRepository<YearlySavingsStatisticMongoEntity>
